version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    volumes:
      - mysql_laa:/var/lib/mysql:delegated
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web:
    build: .
    command: bash -c "entrypoint.sh && bash init.sh"
    restart: on-failure
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - KAFKA_HOST=kafkabroker
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6380:6379'
    volumes:
      - ./volumes/redis-data:/data
volumes:
  bundle:
  mysql_laa:
  redis:
